### ISSUE TITLE
Support choosing language model as a configuration

### ISSUE THREAD

**Issue by ozanani** [swark-io/swark#2]
VS Code Language Model API now supports additional language models, such as: `gpt-4o, gpt-4o-mini, o1-preview, o1-mini, claude-3.5-sonnet, gemini-1.5-pro`
Source: https://code.visualstudio.com/api/extension-guides/language-model#send-the-language-model-request

Add a new configuration setting named `swark.languageModelFamily`, to allow the user setting the language model they prefer. 
This is the line that selects the language model:
https://github.com/swark-io/swark/blob/dc9d84f90b58fbcc79afa7ece77e83bd8e743e7f/src/llm/model-interactor.ts#L6

**Comment by buger** [comment]
Just raised a PR #3 

----
I found your project via https://helpwanted.dev/
Spread the word about it, to help smaller OSS projects find its contributors :)

**Comment by ZuzooVn** [comment]
Can you support Other Models from Git Coplot with an API key, such as Gemini 2.5 Flash Preview?

**Comment by ozanani** [comment]
Do you mean that Gemini 2.5 Flash is available for you, but you cannot choose this in Swark's settings?
