### ISSUE TITLE
Feature Request: Include Direct Link to Generated Mermaid Diagram in Output

### ISSUE THREAD

**Issue by ofir5300** [swark-io/swark#4]
Hello,

I would like to request an enhancement to the generated output of swark. Could you please add a link that includes the payload of the generated Mermaid diagram? This would allow users to automatically view the generated diagram upon clicking the link.

Benefits:
	•	Improved User Experience: Users can instantly visualize their diagrams without manually copying and pasting the Mermaid code.
	•	No Need for Additional Extensions: Users can view the diagrams without requiring any extra Mermaid extensions in VSCode or other editors.
	•	Efficiency: Streamlines the workflow by reducing extra steps.
	•	Accessibility: Makes it easier for users to share and collaborate on diagrams.

Proposed Solution:
	•	Integrate a feature that appends the Mermaid diagram code to a URL of a Mermaid live editor or viewer.
	•	Example link format: https://mermaid.live/edit#pako:<compressed_payload>

Thank you for considering this feature. It would greatly enhance the usability of swark for all users, especially for those who do not have additional extensions installed.

**Comment by ozanani** [comment]
Thanks for the proposal @ofir5300 ! 
This could be a good addition. Initially I planned on having this, but did not find any documentation/API on how to create the mermaid link. Mermaid is open source so with a bit of a research we can do it.

**Comment by ozanani** [comment]
Implemented in 3f17783 and will be released soon.

https://github.com/user-attachments/assets/96ad620f-cdea-433b-b39e-a2953e3e5def
